language: node_js
node_js:
- 0.12
- 4.1
- 4.2
- 5.0
- 5.1
- 5.2
- 5.3
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: dave@etianen.com
  api_key:
    secure: mWeDTw4IOUrybj94mdiOvWuYK4mIKJHtXpnO6ImPamhIMNHuHGRSjYo9I9OnBnvNznCyVA5Nne4M8swwE0KRj+CPiuhqxnTqcddn866O7FlEzs3bmvkD9KmM0NinMPEgLnOuLeP8s5JfYQiz222EfqdkZu4eu99Qzoa4P3xAh7C8Aoh8yzdC/bZcLH/Z61y5C3nMOvNPVp/3N/Ume9XmM2zry9fDYu3UfEPPYDE8DLP7kmuj+lX3ey85t0HYhVaMPhSGAXaQMB2ynqUM+Op+KnGPz+OmKvIDFVWV5aEacI9BPe06QyEd+Mak9pYwx3r/MPh/QmMTwnsJkOfmFB3nqXKahzUTUqk7KD1I7YpL72lRziu1nhjMtCVZZBewYLX3SsVfnUDrQ0rYDSdOc7B/Dtg315Fl/bWO5x4Mi8cCA+zEcHzn+xexhHB3E/cTLd49Mz3SrurZn7XEX5+YNBV3VJ2nxvxCPgpHoQyIWZOuBNf2LkIV4SH5gDFwqj2JHSGCJDrHeBQN2zCXJ6zoIVyFu1WmRzDPcR00Ix1KEv1wOdP5OP2WrO7PxcuSiwAIiFle1xJglySDTXuygwb/L3nleqHBC73kQJ/486c0rjSpAHz1c20192UqWn9Aws1SN8lVcPG1uFNfYeGyRjfZsdoUUq6by4rjcmmRtBClLCLQG00=
  skip_cleanup: true
  on:
    tags: true
    repo: etianen/state-machine
notifications:
  on_success: never
  on_failure: change
